sdm632-common: Make shim for libmot_gpu_mapper
P: GraphicBuffer::lock(uint32_t inUsage, void** vaddr);
Q: GraphicBuffer::lock(uint32_t inUsage, void** vaddr, int32_t* outBytesPerPixel, int32_t* outBytesPerStride);
Error: cannot locate symbol "_ZN7android13GraphicBuffer4lockEjPPv" referenced by "/vendor/lib/libmot_gpu_mapper.so"

Change-Id: I1c1fe66f3f73149ced601eae87b970ce392d50ee

Conflicts:
	AndroidProducts.mk
	device.mk
	extract-files.sh
	libshims/Android.mk